use_default_settings: true

server:
  secret_key: "ryx-searxng-secret-key-2024"
  limiter: false
  image_proxy: true
  
search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
    - json

general:
  debug: false
  instance_name: "Ryx Search"

ui:
  static_use_hash: true
  
outgoing:
  request_timeout: 10.0
  max_request_timeout: 30.0
